version: '2'

services:

  traefik:
    image: 'traefik:v2.9'
    container_name: 'traefik'
    command:
      - '--log.level=DEBUG'
      - '--api=true'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.websecure.address=:443'
      - '--providers.docker.exposedbydefault=true'
      - '--certificatesresolvers.le.acme.tlschallenge=true'
      - '--certificatesresolvers.le.acme.email=lespinerua@gmail.com'
      - '--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - './letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - traefik-net

  # api:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   image: api
  #   container_name: app
  #   # env_file: ./apps/api/src/variables.env
  #   restart: unless-stopped
  #   ports:
  #     - '3000'
  #   mem_limit: 2g
  #   memswap_limit: -1
  #   mem_swappiness: 20
  #   labels:
  #     - 'traefik.enable=true'
  #     - 'traefik.http.routers.api.rule=Host(`demo.lesanpi.dev`)'
  #     - 'traefik.http.routers.api.entrypoints=websecure'
  #     - 'traefik.http.routers.api.tls.certresolver=le'
  #   networks:
  #     - traefik-net

  jenkins:
    image: jenkins/jenkins:jdk17
    container_name: jenkins
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - jenkins_home:/var/jenkins_home
    # restart: always
    restart: unless-stopped
    privileged: true
    user: root
    # ports:
    #   - '8080'
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.lesanpi.dev`)"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      # - 'traefik.enable=true'
      # - 'traefik.port=8080'
      # - 'traefik.http.routers.api.rule=Host(`jenkins.lesanpi.dev`)'
      # - 'traefik.http.routers.api.entrypoints=websecure'
      # - 'traefik.http.routers.api.tls.certresolver=le'
      # - 'traefik.http.services.api.loadbalancer.server.port=8080'
    networks:
      - traefik-net
    environment:
      - "TZ=America/Caracas"
      - "JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dhudson.footerURL=https://demo.lesanpi.dev"

networks:
  traefik-net:
    driver: bridge
